### ISSUE TITLE
Adding some more C++ programs

### ISSUE THREAD

**Issue by simrann20** [iampavangandhi/CodingPracticals#1]
Hi, 
I would like to contribute to this repo by adding more C++ programs as part of my Hacktoberfest contributions.
@iampavangandhi

**Comment by simrann20** [comment]
Can I make some PRs?

**Comment by iampavangandhi** [comment]
Hey @simrann20 yes you can contribute in it by adding more questions. One more thing you can do is to rename the existed .cpp, .java and .py files on the basis of the code written inside it.

**Comment by simrann20** [comment]
Sure, thanks :)

**Comment by ayushhj** [comment]
Hi, @iampavangandhi  I also want to contribute to this repo by adding some programs as a part of Hacktoberfest. Can i do so?

**Comment by iampavangandhi** [comment]
@ayushhj Yes, you can. Also rename the existed .cpp, .java, and .py files on the basis of the code written inside it to make it easy for everyone to use those files

@simrann20
