### ISSUE TITLE
Add or Improve the Programs

### ISSUE THREAD

**Issue by iampavangandhi** [iampavangandhi/CodingPracticals#6]
You can add programs or improve the existing once by renaming them or by adding comments

**Comment by ankurjain00** [comment]
Hi @iampavangandhi I would like to contribute by adding fibonacci in Python

**Comment by Nikzy7** [comment]
Hey ! Check my PR #8

**Comment by ankurjain00** [comment]
@iampavangandhi can I add second largest number in an array?
